### ISSUE TITLE
Nether resetting after installing plugin

### ISSUE THREAD

**Issue by TheInventorDS** [Lauriethefish/BetterPortals#2]
I put this on my server and the Nether reset (I haven't been able to check the end yet). I've follow all the steps to install the plugin, I'm just wondering why it would reset the Nether.

**Comment by Lauriethefish** [comment]
I have no idea why it would reset the nether. (There is nothing that would do this in the code AFAIK.) Are you referring to nether portals losing their destinations? Because there are warnings about that in the plugin description (installing it on existing servers is not ideal, since it redoes portal spawning logic)

**Comment by Lauriethefish** [comment]
I would appreciate if you could reply so that if this is a bug, it can be fixed.

**Comment by Lauriethefish** [comment]
Due to the lack of response for 2 days, I'm gonna close this issue.
