### ISSUE TITLE
Plugin linking vanilla portals when walking through to the other side

### ISSUE THREAD

**Issue by Naharie** [Lauriethefish/BetterPortals#22]
More or less as the title says. Since the last update any time I go through a "vanilla" portal (we're using a datapack to enable using crying obsidian and the plugin doesn't recognize that), the plugin tries to fix it on the other side and fairly consistently guesses the portal to be two blocks wider on the horizontal axis than it really is. If it's helpful, I can grab a clip of this effect tomorrow.

**Comment by Lauriethefish** [comment]
A clip would be great. I think I know what the real issue is, the plugin shouldn't try to add portals that aren't made by the player lighting with flint-and-steel. It should just ignore situations like this entirely.
If you're cool with it, I'll rename this issue.

**Comment by Naharie** [comment]
https://www.youtube.com/watch?v=jvk1Cs350SI
Server is running on paper. The only plugins are BetterPortals and ProtocolLib.
The only datapack that affects portals is the custom portal shapes one.

**Comment by Lauriethefish** [comment]
Fixed this behavior - the plugin should leave vanilla portals as is instead of attempting to link them, since this causes them to have an incorrect size. I know that this might not be the solution you're looking for, but it's the intended behavior in my eyes.

Vanilla portals should now be left as is - except that there is a warning message for them. Which is of course, toggle-able in the config. Worlds where vanilla portal logic is specified also don't have this warning message.

Thanks for the report, should be fixed now.

**Comment by Naharie** [comment]
Great!

"I know that this might not be the solution you're looking for, but it's the intended behavior in my eyes." - true, but now you've added an API, so if it really bothers me in the future, I can write my own plugin to try and make it work that way.

Thanks for fixing it either way.

**Comment by Lauriethefish** [comment]
Mmm, I'm not totally sure you could do this with the API, but you could do it by manually listening to the event then spawning portals.
Anyway.
