### ISSUE TITLE
Instant teleportation toggle

### ISSUE THREAD

**Issue by HerrTechnik** [Lauriethefish/BetterPortals#23]
**What would you like added?**
I could need an option to toggle the instant teleportation when stepping into portals. This could than be configured in the config file or per portal.

**Is it to solve a particular problem?**
There are a lot of people on my server who have their portal like a doorway where you can walk through. Without BetterPortals the normal behaviour is:
Survial Mode: teleportation timer with animation
Creative Mode: instant teleportation
With BetterPortals it's like in creative mode and that's a problem for them. (They can't walk through the portals anymore)

What are your thoughts about this?
Thx

**Comment by Lauriethefish** [comment]
Hmm, just saw that you forked the repository. Do you plan to add this yourself?

**Comment by Lauriethefish** [comment]
Why can't they walk through the portals? I don't really understand why instant teleportation is a problem in this situation.

**Comment by HerrTechnik** [comment]
forking was by mistake

so if you are in survival mode you can easily walk through portals without getting tped (without BP), but with BP it's like you are in creative mode where you will get tped instantly.

**Comment by HerrTechnik** [comment]
They placed the portal in the hallway and want to be able to use it from either side but also to walk through without getting tped

**Comment by Lauriethefish** [comment]
The slight problem here is that BetterPortals doesn't "implement instant teleportation", but more it "overrides all teleportation". This is because it also overrides portal linking, and allowing vanilla linking to happen would break the overridden portal linking. Adding a "toggle" would also involve re-implementing slow teleportation, which isn't something I'm interested in right now.

It'll be a while before this gets added.

**Comment by HerrTechnik** [comment]
ahh okay, seeing your point. I'm okay with that.
k well thanks for the instant reply and great plugin you have there, will be using it anyway ;)
